apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 391ee6ff-09f4-41c9-b953-f267d83caf9f
    keyvaultName: bigk8skv
    tenantId: 472e65d1-2699-467c-a45f-fb1cce060f34
    objects: |
      array:
        - |
          objectName: acr-password
          objectType: secret

