apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 14d5c8df-3c26-4bd8-bf9c-dbbd01568aa7
    keyvaultName: "bigk8skv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: acr-password
          objectType: secret
    tenantId: 472e65d1-2699-467c-a45f-fb1cce060f34
  secretObjects:
  - secretName: acr-password
    type: Opaque
    data:
    - objectName: acr-password
      key: acr-password
