apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  creationTimestamp: "2025-10-23T12:04:21Z"
  generation: 1
  name: azure-kv-secrets
  namespace: default
  resourceVersion: "1494276"
  uid: 42ae9ed1-e0db-4ee6-a05e-e0d88f23eeb8
spec:
  parameters:
    cloudName: ""
    keyvaultName: bigk8skv
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
    tenantId: 472e65d1-2699-467c-a45f-fb1cce060f34
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 14d5c8df-3c26-4bd8-bf9c-dbbd01568aa7
  provider: azure
  secretObjects:
  - data:
    - key: SQL_CONNECTION_STRING
      objectName: db-connection-string
    secretName: sql-conn-k8s
    type: Opaque
