name: CI/CD - Build and Deploy Node App

on:
  push:
    branches:
      - main
    paths:
      - "node-app/**"
      - "node-app-chart/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Get secret from Azure Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: big2025vault
          secrets: 'acr-password'
        id: getSecrets
      
      - name: Build Docker image
        run: |
          IMAGE_TAG=v${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/node-app:$IMAGE_TAG ./node-app

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/node-app:${{ env.IMAGE_TAG }}

      - name: Update Helm chart image tag
        run: |
          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" node-app-chart/values.yaml

      - name: Commit updated Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add node-app-chart/values.yaml
          git commit -m "Update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push
